# Numpy


This part focuses on Numpy, see <a href="http://cs.haverford.edu/faculty/smathieson/teaching/f19/labs/lab01/lab01.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 1 

Create a null vector of size 10 (that is a vector that includes 10 zeros) and print it

In [1]:
#solution
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Problem 2
Create a null vector of size 10 but the fifth value which is 1 

In [2]:
#Solution of Problem 2
import numpy as np
a = np.zeros(10)
a[4,] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Problem 3
Create a vector with all integer values ranging from 10 to 49 

In [8]:
#Solution of Problem 3
import numpy as np
a = np.random.randint(10, 49, size=10)
print(a)

[30 13 40 32 41 44 42 43 12 10]


# Problem 4
 Create a 3x3 matrix with values ranging from 0 to 8 

In [11]:
#Solution of Problem 4
import numpy as np
a = np.random.randint(0, 8, size=(3,3))
print(a)

[[3 5 6]
 [6 5 7]
 [5 5 1]]


# Problem 5
Find indices of non-zero elements from [1,2,0,0,4,0]

In [68]:
#Solution of Problem 5
import numpy as np
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4]),)

# Problem 6
Create a 3x3 identity matrix

In [14]:
#Solution of Problem 6
import numpy as np
a = np.eye(3,3, dtype="int32")
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Problem 7
Create a 3x3x3 array with random values (you can use ` np.random.random`)

In [18]:
#Solution of Problem 7
import numpy as np
a = np.random.random(size=(3,3,3))
print(a)

[[[0.91243526 0.28155767 0.84573805]
  [0.33746464 0.55666527 0.19029453]
  [0.039912   0.60687185 0.16274127]]

 [[0.66622287 0.57553441 0.51354262]
  [0.25051975 0.09110364 0.95719011]
  [0.30914562 0.6139765  0.120383  ]]

 [[0.99181161 0.95678906 0.26856056]
  [0.5488123  0.70241688 0.82100684]
  [0.35097578 0.20050488 0.70713511]]]


# Problem 8
 Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
#Solution of Problem 8
import numpy as np
a = np.random.randint(0, 99, size=(10,10))
max_value = np.max(a)
min_value = np.min(a)
print(a)
print("Max Value: ", max_value)
print("Min Value: ", min_value)

[[42 40 32 25 67 38 62 27 15 40]
 [53 96 11 23 59 64 38 42 13 65]
 [41 28 57 55 22 49 23 43 56 15]
 [34 29 58 80  3  6 66 16 72  9]
 [91 90 93 26 27 62 62 28 36 66]
 [32 49 55 69  9 39 74 50 92 91]
 [70 36 89 58 26 33  9 74 46 89]
 [17 82 36 47  6 22 14 44 62  9]
 [ 8 30  8  3 68 15  7 67  3 30]
 [45 61 43 62  8 47 60 26 96 59]]
Max Value:  96
Min Value:  3


# Problem 9
Create a random vector of size 30 and find the mean value 


In [25]:
#Solution of Problem 9
import numpy as np
a = np.random.random(size=(30))
print("Mean Value: ", np.mean(a))

Mean Value:  0.5192091836516389


# Problem 10

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
#Solution of Problem 10
import numpy as np
a = np.random.randint(1,5, size=(5, 5))
b = np.tril(a, -1)
print(b)

[[0 0 0 0 0]
 [4 0 0 0 0]
 [3 4 0 0 0]
 [2 3 2 0 0]
 [2 2 4 4 0]]


# Problem 11
Normalize a 5x5 random matrix

Solution:
>Z = np.random.random((5,5))
>
>Z = (Z - np.mean (Z)) / (np.std (Z))
>
>print(Z)


In [43]:
#Solution of Problem 11
import numpy as np
a = np.random.random((5,5))
a = (a-np.mean(a))/(np.std(a))
print(a)

[[ 0.9727634   0.0365054  -0.44370678  1.17419912 -1.18814858]
 [ 0.58920176  1.36671631 -0.60374885 -0.39658258  0.18474367]
 [-1.0639673  -0.96745164 -1.691497    0.18338493 -0.51859943]
 [ 1.39847661  1.25220757  1.53500812  1.26462249 -0.26697873]
 [-1.25901953 -1.44351799 -0.84041908  1.02367157 -0.29786348]]


# Problem 12

Multiply a 5x3 matrix by a 3x2 matrix (matrix product)

In [51]:
#Solution of Problem 12
import numpy as np
a = np.random.randint(0, 10, size=(5, 3))
b = np.random.randint(0, 10, size=(3, 2))
c = np.matmul(a, b)
print(c)

[[60 84]
 [54 72]
 [ 6 57]
 [48 96]
 [60 75]]


# Problem 13
Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [78]:
#Solution of Problem 13
import numpy as np
a = np.arange(10)
b = np.negative(np.where((a > 3) & (a < 8)))
print(a)
print(b)
a[4:8] = b
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[-4 -5 -6 -7]]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


# Problem 14
How to find common values between two arrays?


In [88]:
#Solution of Problem 11
import numpy as np
a = np.random.randint(0, 99, size=(3,6))
b = np.random.randint(0, 99, size=(3,6))
c = np.intersect1d(a, b)
print("A:\n",a, "\nB:\n",b)
print("Common Values:\n", c)

A:
 [[86  8 55 88 80 78]
 [66 14 89 27 43 39]
 [12 69 36 61 94 18]] 
B:
 [[44 95 80  0 51 86]
 [78  1 93 73 20 46]
 [74 82 96 70 40  9]]
Common Values:
 [78 80 86]


# Problem 15
 Create a random vector of size 10 and sort it 


In [82]:
#Solution of Problem 15
import numpy as np
a = np.random.random(size=10)
b = np.sort(a)
print("Random Vector--->\n", a)
print("Sorted Vector--->\n", b)

Random Vector--->
 [0.63126776 0.82900405 0.57793588 0.13688406 0.67906406 0.65202201
 0.30964967 0.49755561 0.11187827 0.43775306]
Sorted Vector--->
 [0.11187827 0.13688406 0.30964967 0.43775306 0.49755561 0.57793588
 0.63126776 0.65202201 0.67906406 0.82900405]


# Problem 16
Subtract the mean of each row of a matrix (Use `X = np.random.rand(5, 10)` to generate the array)

In [29]:
#Solution of Problem 16
import numpy as np
X = np.random.rand(5, 10)
Y = np.mean(X, 1).reshape(5,1)
b = np.subtract(X[:], Y[:])
print("A------->\n", X)
print("Row Mean------->\n",Y)
print("Resultant Array---------->\n", b)

A------->
 [[0.50960381 0.88839434 0.48100546 0.21187854 0.55335685 0.03500322
  0.45255099 0.03173355 0.83330041 0.36475625]
 [0.49054718 0.90799503 0.73554034 0.7031341  0.86185166 0.07463618
  0.02040045 0.15984325 0.56588396 0.58063055]
 [0.87106393 0.3944306  0.21300156 0.92434805 0.56663963 0.84675157
  0.98944965 0.06371799 0.16739721 0.88905372]
 [0.72201826 0.34773664 0.19733373 0.03026188 0.77080948 0.27150563
  0.22607152 0.75428868 0.6883606  0.05450653]
 [0.01075632 0.64442915 0.35480085 0.1193006  0.43079091 0.99142346
  0.97101468 0.5463919  0.26612785 0.72294188]]
Row Mean------->
 [[0.43615834]
 [0.51004627]
 [0.59258539]
 [0.4062893 ]
 [0.50579776]]
Resultant Array---------->
 [[ 0.07344547  0.452236    0.04484712 -0.2242798   0.11719851 -0.40115512
   0.01639265 -0.40442479  0.39714207 -0.07140209]
 [-0.01949909  0.39794876  0.22549407  0.19308783  0.35180539 -0.43541009
  -0.48964582 -0.35020302  0.05583769  0.07058428]
 [ 0.27847853 -0.19815479 -0.37958383  0.33176

# Problem 17
Find the nearest value from a given value in an array (Use `Z = np.random.uniform(0,1,10)` to generate the array)

In [17]:
#Solution of Problem 17
import numpy as np
Z = np.random.uniform(0, 1, 10)
value = float(np.random.random(1))
idx = (np.abs((Z - value))).argmin()
nearest_value = Z[idx]
print("Nearest value:--------->\n", nearest_value)

Nearest value:--------->
 0.5060312201116851


# Problem 18
How to find the most frequent value in an array? (Use `Z = np.random.randint(0,10,50)` to generate the array)

In [23]:
#Solution of Problem 18
import numpy as np
Z = np.random.randint(0,10,50)
freq = np.argmax(np.bincount(Z))
print("Array ----------->\n", Z)
print("Most Frequest Value: ", freq)

Array ----------->
 [9 2 1 4 9 3 7 3 8 0 6 3 1 5 8 0 1 1 3 8 4 3 7 6 6 8 3 2 7 3 7 3 2 7 6 4 6
 2 6 5 5 1 6 1 9 3 3 3 2 6]
Most Frequest Value:  3


# Problem 19: Multiple exercises about Array creation and modification

In [24]:
import numpy as np
# create a 4x5 array of zeros

m = np.zeros([4,5])
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# create a 3x5 array of zeros using reshape
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
# create an array from a list
b = np.array([6, 7, 8])
b

array([6, 7, 8])

**Questions**
1. Use the `.shape` attribute to find the shape of `m`, `a`, and `b` above
2. Change several of the entries of `m` using assignment (similar to lists, i.e. `m[2][1]`)
3. To what dimensions could you `reshape` `m`? Try out a few of these to see how the entries behave.
4. What does `reshape` do when -1 is used as part of the shape? For multi-dimensional arrays, how many dimensions can be specified with -1.



In [56]:
#Answer to Question 1
print("Shape of m: ", m.shape)
print("Shape of a: ", a.shape)
print("Shape of b: ", b.shape)
#Answer to Question 2
m[2, 1] = 9
m[0,1] = 5
m[3,4] = 3
m[0,4] = 1
#Answer to question 3
#Reshape 1
m_1 = np.reshape(m, (5,4))
print("Reshaped M-1:------>\n",m_1)
print("Size of M-1: ", m_1.shape)
#Reshape 2
m_2 = np.reshape(m, (2,10))
print("Reshaped M-2:------>\n",m_2)
print("Size of M-2: ", m_2.shape)
#Reshape 3
m_3 = np.reshape(m, (1,20))
print("Reshaped M-3:------>\n",m_3)
print("Size of M-3: ", m_3.shape)
#Answer to question 4
print("Original B=======>\n", b)
#Reshape for B -1
b_1 = np.reshape(b, (-1))
print("Reshaped B-1:------>\n",b_1)
print("Size of B-1: ", b_1.shape)
#Reshape for B-2
b_2 = np.reshape(b, (-5, 5))
print("Reshaped B-2:------>\n",b_2)
print("Size of B-2: ", b_2.shape)

Shape of m:  (4, 5)
Shape of a:  (10,)
Shape of b:  (5, 10)
Reshaped M-1:------>
 [[0. 5. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 9.]
 [0. 0. 0. 0.]
 [0. 0. 0. 3.]]
Size of M-1:  (5, 4)
Reshaped M-2:------>
 [[0. 5. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 3.]]
Size of M-2:  (2, 10)
Reshaped M-3:------>
 [[0. 5. 0. 0. 1. 0. 0. 0. 0. 0. 0. 9. 0. 0. 0. 0. 0. 0. 0. 3.]]
Size of M-3:  (1, 20)
Original B=======>
 [[ 0.07344547  0.452236    0.04484712 -0.2242798   0.11719851 -0.40115512
   0.01639265 -0.40442479  0.39714207 -0.07140209]
 [-0.01949909  0.39794876  0.22549407  0.19308783  0.35180539 -0.43541009
  -0.48964582 -0.35020302  0.05583769  0.07058428]
 [ 0.27847853 -0.19815479 -0.37958383  0.33176266 -0.02594576  0.25416618
   0.39686426 -0.5288674  -0.42518818  0.29646833]
 [ 0.31572896 -0.05855266 -0.20895556 -0.37602741  0.36452018 -0.13478367
  -0.18021777  0.34799939  0.28207131 -0.35178277]
 [-0.49504144  0.13863139 -0.15099692 -0.38649716 -0.07500685  0.4856257
   0.4652

# Problem 20: Multiple exercises about Array slicing and concatenation

Try out the slicing operations below, predicting what will be printed each time. Make sure you have modified the m array enough that output is clear.

In [58]:
print(m)
print(m[2],'\n\n',m[:,1],'\n\n', m[:3,:2])

[[0. 5. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 3.]]
[0. 9. 0. 0. 0.] 

 [5. 0. 9. 0.] 

 [[0. 5.]
 [0. 0.]
 [0. 9.]]


**Exercises**
1. Look up the `concatenate` function and apply it to your `m` array and `a` array to produce an 7x5 array.
2. Look up the `sort` function (from `numpy`) and apply it to both axes of your `m` array (as well as `axis=None`) and make sure the output makes sense.

In [77]:
m = np.reshape(m, (2,10))
a = np.reshape(a, (2, 5))
c = np.concatenate((m, a), axis = 1)
print(c, c.shape)
m_sort = np.sort(m, axis=1)
print("Sorted M:========>\n", m_sort)
m_sort1 = np.sort(m, axis=None)
print("Sorted M-1:========>\n", m_sort1)

[[0.         5.         0.         0.         1.         0.
  0.         0.         0.         0.         0.50960381 0.88839434
  0.48100546 0.21187854 0.55335685]
 [0.         9.         0.         0.         0.         0.
  0.         0.         0.         3.         0.03500322 0.45255099
  0.03173355 0.83330041 0.36475625]] (2, 15)
Sorted M:========>
 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 9.]]
Sorted M-1:========>
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 3. 5. 9.]
